### ISSUE TITLE
2020春招-腾讯WXG web前端开发 一二三+HR面经 - Ricky's realm

### ISSUE THREAD

**Issue by rickypeng99** [rickypeng99/rickypeng99.github.io#14]
http://rickypeng.com/2020/04/17/tencent.html 

 腾讯WXG前端实习一二三+HR面经 2020春招这次春招我一共参加了8次腾讯春招实习面试。。其中PCG是三月份参加的一二三面，挂在三面，然后被TEG下面的CDC捞起来参加了一面（不知道为啥这个一面挂了我其实觉得聊得挺好的哈哈哈）。感谢最后被WXG再次捞了起来。我就讲讲WXG吧！其他的有点忘了

**Comment by Amadeus-cyf** [comment]
太强了啊啊啊啊啊啊啊啊啊啊
